# Generated by Django 2.2.1 on 2019-05-02 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_url', models.URLField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='LinkPointer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='glue.Link')),
            ],
        ),
    ]
